micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: jdbc:mariadb://localhost:4000/pokemon
    username: example-user
    password: my_cool_secret
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update