micronaut:
  application:
    name: pokemon
  server:
    port: 5000
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driver-class-name: ${DATASOURCE_DEFAULT_DRIVER:org.mariadb.jdbc.Driver}
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: ${DATASOURCE_DEFAULT_URL:`jdbc:mariadb://localhost:3306/pokemon`}
    username: ${DATASOURCE_DEFAULT_USER:mahesh}
    password: ${DATASOURCE_DEFAULT_PASSWORD:12345678}
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml