name: Gradle Package

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Test and Build with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Run gradle build
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pokemon-api-jar
          path: build/libs/demo-0.1-all.jar
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: pokemon-api-jar
      - name: List Directory
        run: ls
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: pokemon-api
          environment_name: Pokemonapi-env
          version_label: ${{ github.sha }}
          region: ap-south-1
          deployment_package: demo-0.1-all.jar
